(import :std/make :std/test :std/test/base)

(def directory (getenv "D885_FIXTURE"))
(def root (getenv "GERBIL_PATH"))
(def cores (string->number (getenv "GERBIL_BUILD_CORES")))
(def modules (call-with-input-file (path-expand "modules.scm" directory) read))
(def spec
  (map (lambda (name) `(gxc: ,name "-keep-temp" "-cc-options" "-ftime-report"))
       modules))
(def (emit value)
  (write value) (newline) (force-output))
(def (timed name thunk)
  (emit `(PHASE-START ,name))
  (let* ((start (time->seconds (current-time))) (result (thunk)))
    (emit `(PHASE-END ,name ,(- (time->seconds (current-time)) start)))
    result))
(def (build)
  (make spec srcdir: directory parallelize: cores optimize: #t verbose: 2))
(def (native-stamps)
  (map (lambda (name)
         (let (path (path-expand (string-append "lib/d885/" name ".o1") root))
           (unless (file-exists? path) (error "missing native output" path))
           (time->seconds (file-info-last-modification-time (file-info path)))))
       modules))
(def (dependency-stamps)
  (map (lambda (name)
         (map (lambda (relative)
                (time->seconds
                 (file-info-last-modification-time (file-info (path-expand relative root)))))
              (list (string-append "lib/d885/" name ".ssi")
                    (string-append "lib/static/d885__" name ".scm"))))
       modules))
(def suite
  (test-suite "parallel std/make build contract"
    (test-case "cold build produces native modules"
      (timed 'cold build)
      (check (length (native-stamps)) => (length modules))
      (eval '(import :d885/join))
      (check (eval '(answer 1)) => 242))
    (test-case "warm no-op schedules no compilation"
      (let* ((before (native-stamps))
             (output (timed 'noop (lambda () (with-output-to-string build)))))
        (check output => "")
        (check (native-stamps) => before)))
    (test-case "dependency invalidation preserves unrelated modules"
      (let ((before (dependency-stamps)) (native-before (native-stamps)))
        (thread-sleep! 1.1)
        (let (path (path-expand "left.ss" directory))
          (let (source (call-with-input-file path (lambda (p) (read-line p #f))))
            (call-with-output-file path (lambda (p) (display source p)))))
        (let (output (timed 'incremental (lambda () (with-output-to-string build))))
          (emit `(BUILD-OUTPUT ,output))
          (check (filter (cut string-prefix? "... compile " <>)
                         (string-split output #\newline))
                 => '("... compile left" "... compile join")))
        (let (after (dependency-stamps))
          (for-each
           (lambda (old new)
             (for-each (lambda (a b) (check (> b a) => #t)) old new))
           (take before 2) (take after 2))
          (check (cddr after) => (cddr before))
          (check (cddr (native-stamps)) => (cddr native-before)))))))
(emit '(READY std-make-test))
(parameterize ((current-test-config (TestConfig verbosity: 5 capture-output?: #f)))
  (unless (test-result-ok? (test-suite! suite)) (error "parallel make contract failed")))
(emit '(D885-OK))
