(define (check name value)
  (if value (begin (display "CASE-OK ") (display name) (newline) (force-output))
      (error "Darwin buffered token control failed" name)))
(check "actual token entry enabled" (procedure? ##gb-darwin-buffered-token))
(define (token text c i)
  (let ((port (open-input-string text)))
    (peek-char port)
    (let ((result (##gb-darwin-buffered-token (get-readenv port) c i)))
      (cons result (peek-char port)))))
(check "complete token and delimiter retained" (equal? (token "foo bar" #\space 0) '("foo" . #\space)))
(check "initial character prefix preserved" (equal? (token "foo " #\x 1) '("xfoo" . #\space)))
(check "general prefix count preserved" (equal? (token "foo " #\x 3) '("xxxfoo" . #\space)))
(check "empty token falls back without consumption" (equal? (token " " #\x 1) '(#f . #\space)))
(check "EOF token falls back without consumption" (equal? (token "foo" #\x 1) '(#f . #\f)))
(check "long token bounded fallback"
  (equal? (token (string-append (make-string 300 #\a) " ") #\x 1) '(#f . #\a)))
(check "large prefix bounded fallback" (equal? (token "foo " #\x 4097) '(#f . #\f)))
(define unicode (integer->char 955))
(check "Unicode tail falls back without consumption"
  (equal? (token (string-append (string unicode) "foo ") #\x 1) (cons #f unicode)))
(for-each
  (lambda (row)
    (check (string-append "real reader: " (car row))
      (equal? (call-with-input-string (string-append (car row) " ") read) (cdr row))))
  (list (cons "identifier" 'identifier) (cons "-17" -17) (cons "3.125" 3.125)
        (cons "1/3" 1/3) (cons "1+2i" 1+2i) (cons "hello:" hello:)
        (cons "#t" #t) (cons "|escaped name|" (string->symbol "escaped name"))))
(check "real Unicode reader unchanged"
  (equal? (call-with-input-string (string-append "x" (string unicode) "foo ") read)
          (string->symbol (string-append "x" (string unicode) "foo"))))
(check "actual bounded fallback reader unchanged"
  (equal? (call-with-input-string (string-append (make-string 300 #\a) " ") read)
          (string->symbol (make-string 300 #\a))))
(let* ((rt (##readtable-copy (current-readtable))) (port (open-input-string "foo!rest")))
  (##readtable-char-delimiter?-set! rt #\! #t)
  (peek-char port)
  (parameterize ((current-readtable rt))
    (check "custom delimiter table honored"
      (equal? (##gb-darwin-buffered-token (get-readenv port) #\x 1) "xfoo")))
  (check "custom delimiter unconsumed" (char=? (peek-char port) #\!)))
(let* ((rt (##readtable-copy (current-readtable))) (port (open-input-string "foo\nbar ")))
  (##readtable-char-delimiter?-set! rt #\newline #f)
  (peek-char port)
  (parameterize ((current-readtable rt))
    (check "non-delimiter newline retained in token"
      (equal? (##gb-darwin-buffered-token (get-readenv port) #\x 1) "xfoo\nbar")))
  (check "line and column position accounting retained"
    (and (= (input-port-line port) 2) (= (input-port-column port) 4))))
(let ((port (open-input-string "foo bar ")))
  (peek-char port)
  (##gb-darwin-buffered-token (get-readenv port) #\space 0)
  (read-char port)
  (##gc)
  (check "buffer and readenv survive GC"
    (equal? (##gb-darwin-buffered-token (get-readenv port) #\space 0) "bar")))
(display "OK") (newline) (force-output)
