(load (getenv "READER_TOKEN_CONTROLS"))
(check "actual whitespace entry enabled" (procedure? ##gb-darwin-buffered-whitespace))
(define (skip text)
  (let ((port (open-input-string text)))
    (peek-char port)
    (let ((count (##gb-darwin-buffered-whitespace (get-readenv port))))
      (cons count (peek-char port)))))
(check "buffered whitespace stops before datum" (equal? (skip " \t\nfoo") '(3 . #\f)))
(check "empty buffer unchanged" (equal? (skip "") (cons 0 (eof-object))))
(check "non-whitespace unchanged" (equal? (skip "foo") '(0 . #\f)))
(check "comment prefix unconsumed" (equal? (skip "  ; comment") '(2 . #\;)))
(check "Unicode buffer falls back without consumption"
  (equal? (skip (string unicode)) (cons 0 unicode)))
(let ((rt (##readtable-copy (current-readtable))))
  (##readtable-char-handler-set! rt #\a ##read-whitespace)
  (##readtable-char-delimiter?-set! rt #\a #t)
  (parameterize ((current-readtable rt))
    (check "custom ASCII whitespace handler honored" (equal? (skip "aa foo") '(3 . #\f)))))
(let ((rt (##readtable-copy (current-readtable))))
  (##readtable-char-handler-set! rt #\space ##read-single-line-comment)
  (parameterize ((current-readtable rt))
    (check "custom non-whitespace handler stops batch" (equal? (skip " foo") '(0 . #\space)))))
(let ((rt (##readtable-copy (current-readtable))))
  (##readtable-char-handler-set! rt unicode ##read-whitespace)
  (##readtable-char-delimiter?-set! rt unicode #t)
  (parameterize ((current-readtable rt))
    (check "actual Unicode whitespace fallback unchanged"
      (equal? (call-with-input-string (string-append (string unicode) "  foo ") read) 'foo))))
(for-each
 (lambda (row)
   (check (string-append "actual whitespace reader " (car row))
     (equal? (call-with-input-string (string-append " \t\n  " (car row) " \n") read) (cdr row))))
 (list (cons "foo" 'foo) (cons "17" 17) (cons "1/3" 1/3) (cons "(a b c)" '(a b c))
       (cons "#(1 2)" '#(1 2)) (cons "\"a b\"" "a b")
       (cons "; line\nfoo" 'foo) (cons "#| outer #| inner |# |# foo" 'foo)))
(check "long whitespace spans preserve actual read"
  (equal? (call-with-input-string (string-append (make-string 8193 #\space) "foo ") read) 'foo))
(let ((candidate (open-input-string " \n\t\r foo"))
      (reference (open-input-string " \n\t\r foo")))
  (peek-char candidate)
  (##gb-darwin-buffered-whitespace (get-readenv candidate))
  (let loop ((n 5)) (if (> n 0) (begin (read-char reference) (loop (- n 1)))))
  (check "line and column match actual read-char sequence"
    (and (= (input-port-line candidate) (input-port-line reference))
         (= (input-port-column candidate) (input-port-column reference))
         (char=? (peek-char candidate) (peek-char reference)))))
(let ((port (open-input-string (string-append (make-string 4100 #\space) "foo"))))
  (peek-char port)
  (let ((first (##gb-darwin-buffered-whitespace (get-readenv port))))
    (##gc)
    (check "GC between bounded whitespace chunks"
      (and (= first 32)
           (let loop ((total first) (chunks 1))
             (if (char=? (peek-char port) #\f)
                 (and (= total 4100) (= chunks 129))
                 (let ((n (##gb-darwin-buffered-whitespace (get-readenv port))))
                   (and (> n 0) (<= n 32) (< chunks 129)
                        (begin (##gc) (loop (+ total n) (+ chunks 1)))))))))))
(check "whitespace EOF unchanged"
  (eof-object? (call-with-input-string " \t\n  " read)))
(display "OK") (newline) (force-output)
